NodeJS tutorial
ash-sxn/GSoC-2023-docker-based-quickstart pull request #115
Opened 2023-07-25 15:08 UTC by ash-sxn

- I've rebased the python tutorial's branch in this one because the init and teardown scripts were already updated in the Python tutorial.

2023-07-25 19:31 UTC, gounthar reviewed
The port 3000 is also open.

2023-07-26 08:40 UTC, gounthar requested changes
The `3000` port is still opened.

2023-07-26 09:59 UTC, ash-sxn commented
> The `3000` port is still open.

It's because the tutorial needs to use port 3000 for viewing the website 
check it out [here](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/#add-a-final-deliver-stage-to-your-pipeline)

2023-07-26 12:26 UTC, gounthar commented
Fine with me then.
Thanks!

2023-07-26 13:09 UTC, gounthar approved these changes

2023-07-26 13:15 UTC, gounthar commented on 05_nodejs/README.md
> +* `dockerfiles/Dockerfile` is used to create a custom image from the `jenkins/jenkins` image and copies `plugins.txt` and `jenkins.yaml` into the container for plugins installation and JCasC configur
```suggestion

* `dockerfiles/Dockerfile` is used to create a custom image from the `jenkins/jenkins` image and copies `plugins.txt` and `jenkins.yaml` into the container for plugins installation and JCasC configuration.
```

2023-07-26 13:16 UTC, gounthar commented on 05_nodejs/README.md
> +* `dockerfile/agent/Dockerfile` is used to create a custom agent image from `jenkins/ssh-agent` with nodeJS installed to perform the tutorial
```suggestion
* `The dockerfile/agent/Dockerfile` is used to create a custom agent image from `jenkins/ssh-agent` with nodeJS installed , enabling it to perform the tutorial.
```

2023-07-26 13:17 UTC, gounthar commented on 05_nodejs/README.md
> +* `keygen.sh` is a script that generates new ssh-keys in secrets directory everytime it runs and updates the docker compose file with new keys
```suggestion
* `keygen.sh` is a script that generates new `SSH` keys in the secrets directory every time it runs and updates the Docker Compose file with the new keys.
```

2023-07-26 13:18 UTC, gounthar commented on 05_nodejs/README.md
> +* `fork-and-clone.sh` is script that takes github credentials from user and fork and clone a repo used in the tutorial from a docker container using Dockerfile
```suggestion
* `fork-and-clone.sh` is a script that takes GitHub credentials from the user, forks, and clones a repository used in the tutorial from within a Docker container using the Dockerfile.
```

2023-07-26 13:19 UTC, gounthar commented on 05_nodejs/README.md
> +* `gitpodURl.sh` is a script that replace `http://127.0.0.1:8080` with the gitpod appropriate url in the jenkins.yaml file
```suggestion
* `gitpodURl.sh` is a script that replaces `http://127.0.0.1:8080` with the appropriate Gitpod URLin the `jenkins.yaml` file
```

2023-07-26 13:19 UTC, gounthar commented on 05_nodejs/README.md
> +* Make sure you are in the `05_nodejs` directory by using the command `pwd`.
```suggestion

* Make sure you are in the `05_nodejs` directory by using the command `pwd`. 
```

2023-07-26 13:20 UTC, gounthar commented on 05_nodejs/README.md
> +* Run the script with `./keygen.sh` command to generate ssh keys
```suggestion
* Run the script with the `./keygen.sh` command to generate new `SSH` keys 
```

2023-07-26 13:21 UTC, gounthar commented on 05_nodejs/README.md
> +* after the containers are successfully running (check with `docker compose ps`). You can access the controller on [`http://localhost:8080`](http://localhost:8080)
```suggestion
* After the containers are successfully running (check with `docker-compose ps`), you can access the controller by navigating to [`http://localhost:8080/`](http://localhost:8080/).
```

2023-07-26 13:21 UTC, gounthar commented on 05_nodejs/README.md
> +### Steps to follow the [NodeJS Tutorial](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm)
```suggestion

### Steps to follow the [NodeJS Tutorial](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm)
```

2023-07-26 13:23 UTC, gounthar commented on 05_nodejs/README.md
> +  - Make sure you are in `05_nodejs` directory and Dockerfile and fork-and-clone.sh is present there
```suggestion
  - Before proceeding, ensure that you are in the `05_nodejs` directory, and confirm that both the `Dockerfile` and `fork-and-clone.sh` are present in this directory.
```

2023-07-26 13:25 UTC, gounthar commented on 05_nodejs/README.md
> +  - get inside the `simple-node-js-react-npm-app ` with `cd simple-node-js-react-npm-app ` and create a `Jenkinsfile` with this content
```suggestion
  - Go inside the `simple-node-js-react-npm-app` directory by using the command `cd simple-node-js-react-npm-app`.
  - Once inside the directory, create a `Jenkinsfile` and add the specified content to it:
```

2023-07-26 16:19 UTC, gounthar requested changes

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +  - In the Enter an item name field, specify the name for your new Pipeline project (e.g. simple-node-js-react-npm-app ).
```suggestion
  - Save your `Jenkinsfile`.
  - Run the commands `git add .` to add the `Jenkinsfile` to the staging, then run `git commit -m "Add initial Jenkinsfile"` to commit the changes. Finally, run `git push origin master` to push the changes to your forked repo.
 - Go to Jenkins, login, and click "Create new jobs" under "Welcome to Jenkins!".
  - In the "Enter an item name" field, specify the name for your new Pipeline project (e.g., "`simple-node-js-react-npm-app`").
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +  - Click Save to save your new Pipeline project. You’re now ready to begin. Click `Build Now` button to build your project
```suggestion
  - Scroll down and click "Pipeline", then click "OK" at the end of the page.
  - Click the "Pipeline" tab at the top of the page to scroll down to the Pipeline section.
  - In the "Definition" field, choose the "Pipeline script from SCM" option. This option instructs Jenkins to obtain your Pipeline from Source Control Management (SCM), which will be your forked Git repository.
  - From the "SCM" field, choose "Git".
  - In the "Repository URL" field, specify the directory path of your forked repository above, which is `https://github.com/<username>/simple-node-js-react-npm-app.git` (replace `<username>` with your GitHub username).
  - Click "Save" to save your new Pipeline project. You’re now ready to begin. Click the "Build Now" button to build your project.
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +  - Again open your Jenkinsfile and Copy and paste the following Declarative Pipeline syntax under the Build stage of your Jenkinsfile and save the file
```suggestion
  - Once again, open your `Jenkinsfile` and copy and paste the following Declarative Pipeline syntax under the Build stage of your Jenkinsfile. Then, save the file.
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +- [Add a final deliver stage to your Pipeline](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/#add-a-final-deliver-stage-to-your-pipeline)
```suggestion
  - Run the command `git add .` to add the edited `Jenkinsfile` to the staging, then run `git commit -m "Add 'Test' stage"` to commit the changes. Finally, run `git push origin master` to push the changes to your forked repo.
  - Press the "Build Now" button again to run both the Build and Test stages.
 - [Add a final deliver stage to your Pipeline](https://www.jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/#add-a-final-deliver-stage-to-your-pipeline)
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +  - Again open your Jenkinsfile and Copy and paste the following Declarative Pipeline syntax under the Test stage of your Jenkinsfile and save the file
```suggestion
  - Again, open your `Jenkinsfile` and copy-paste the following Declarative Pipeline syntax under the Test stage of your Jenkinsfile. Then, save the file.
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +  - The Press the `Build Now` button again to run Build, Test and Deliver stages
```suggestion
  - Run the command `git add .` to add the edited `Jenkinsfile` to the staging, then run `git commit -m "Add 'Deliver' stage"` to commit the changes. Afterward, run `git push origin master` to push the changes to your forked repository.
  - Press the "Build Now" button again to run the Build, Test, and Deliver stages.
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +It effectively cleans up the resources associated with your Docker Compose environment.
```suggestion
This command stops the containers defined in your Docker Compose file and removes them, along with any networks, volumes, and other resources created by the Compose setup.
It effectively cleans up the resources associated with your Docker Compose environment.
```

2023-07-26 16:19 UTC, gounthar commented on 05_nodejs/README.md
> +This ensures that all resources, including volumes, are removed.
```suggestion
This command will ensure that all associated resources, including named volumes, are removed when bringing down the Docker Compose environment.
```

2023-07-27 07:25 UTC, gounthar reviewed
Thanks.
Now, what about adding the GitHub Action for Node?

2023-07-27 07:27 UTC, gounthar approved these changes
Ok, I've seen the GitHub Action is part of #122 .

2023-07-27 07:27 UTC, merged