Remove proxy warning
ash-sxn/GSoC-2023-docker-based-quickstart pull request #116
Opened 2023-07-25 18:31 UTC by ash-sxn

- fixes #114 
- pinging mentors @gounthar @berviantoleo @jmMeessen

2023-07-25 18:46 UTC, gounthar requested changes
Thanks.
I'll maybe reopen the issue later on to add more details in the documentation, but it's good enough for the time being. 👍

2023-07-25 18:46 UTC, gounthar commented on README.md
> +for more information about this please look [here](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/issues/114)
```suggestion
### Suppressing Jenkins Warning using JCASC

In order to improve the Gitpod experience with Jenkins, we decided to suppress a reverse proxy setup warning in Jenkins.
This warning was causing issues in the Gitpod environment.

To achieve this, we made use of Jenkins Configuration as Code ([JCASC](https://www.jenkins.io/projects/jcasc/)) and added the following property to the JCASC YAML file:

We've added the following property in JCASC YAML file:

```yaml
jenkins:
  disabledAdministrativeMonitors:
    - "hudson.diagnosis.ReverseProxySetupMonitor"
```

For more detailed information about this configuration and the context behind it, please refer to the [corresponding issue](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/issues/114).

```

2023-07-25 18:48 UTC, gounthar approved these changes

2023-07-26 02:58 UTC, berviantoleo approved these changes

2023-07-26 06:57 UTC, merged