Remove bashfiles
ash-sxn/GSoC-2023-docker-based-quickstart pull request #136
Opened 2023-07-27 11:59 UTC by ash-sxn

- fixes #91 
- haven't tested it fully yet but spins up the correct containers with keywords `maven` `python` `node` with `docker compose up -d` 
- `docker compose up -d` for default (controller+agent)
- `docker compose up -d maven` for default (controller+maven agent)
- `docker compose up -d python ` for default (controller+python agent)
- `docker compose up -d node ` for default (controller+node agent)

2023-07-27 12:11 UTC, gounthar requested changes

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +echo Location is $LOC
```suggestion
echo "Location is $LOC"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +ls -artl $LOC
```suggestion
ls -artl "$LOC"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +rm $LOC/conductor_ok
```suggestion
rm "$LOC/conductor_ok"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +mkdir -p $LOC/secrets
```suggestion
mkdir -p "$LOC/secrets"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +rm -fr $LOC/jenkins_agent_ed $LOC/jenkins_agent_ed.pub
```suggestion
rm -fr "$LOC/jenkins_agent_ed" "$LOC/jenkins_agent_ed.pub"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +ssh-keygen -t ed25519 -f $LOC/jenkins_agent_ed -N ""
```suggestion
ssh-keygen -t ed25519 -f "$LOC/jenkins_agent_ed" -N ""
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +chmod 444 $LOC/jenkins_agent_ed
```suggestion
chmod 444 "$LOC/jenkins_agent_ed"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +pubkey=$(cat $LOC/jenkins_agent_ed.pub)
```suggestion
pubkey=$(cat "$LOC/jenkins_agent_ed.pub")
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +echo The public key is $pubkey
```suggestion
echo "The public key is $pubkey"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +echo "$pubkey" > $LOC/authorized_keys && chown 1000:1000 $LOC/authorized_keys
```suggestion
echo "$pubkey" > "$LOC/authorized_keys" && chown 1000:1000 "$LOC/authorized_keys"
```

2023-07-27 12:11 UTC, gounthar commented on dockerfiles/sidekick/keygen.sh
> +echo "OK" > $LOC/conductor_ok
```suggestion
echo "OK" > "$LOC/conductor_ok"
```

2023-07-27 12:18 UTC, gounthar commented
I have this error:

```
desktop-jenkins_agent-1: Name or service not known
SSH Connection failed with IOException: "desktop-jenkins_agent-1: Name or service not known", retrying in 15 seconds. There are 2 more retries left.
desktop-jenkins_agent-1: Name or service not known
SSH Connection failed with IOException: "desktop-jenkins_agent-1: Name or service not known", retrying in 15 seconds. There are 1 more retries left.
desktop-jenkins_agent-1: Name or service not known
ERROR: Connection is not established!
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:988)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.getRemainingAuthMethods(TrileadSSHPublicKeyAuthenticator.java:89)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.canAuthenticate(TrileadSSHPublicKeyAuthenticator.java:81)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:222)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:173)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:878)
	at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I think the agent has not been launched.

2023-07-27 12:19 UTC, gounthar commented
The GitHub Actions tests don't pass anymore (which was expected).

2023-07-27 14:02 UTC, ash-sxn commented
The problem was with the name of the agent containers. I've fixed it now it's working for me.

2023-07-27 15:00 UTC, gounthar commented
You could create another PR, and modify the linked issue (#91) to say it will be close when the next PR (enter the number) will be done.

2023-07-27 15:21 UTC, gounthar commented
And maybe another PR for the tests changes...

2023-07-27 16:09 UTC, gounthar commented
Maven worked for me on GitPod.
Let me try it under Windows.

2023-07-27 16:13 UTC, gounthar commented
It failed:

```
docker compose up maven
[+] Building 53.6s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                          0.2s
 => => transferring dockerfile: 482B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/debian:bookworm                                                                                                            2.9s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                             0.2s
 => => transferring context: 1.07kB                                                                                                                                           0.0s
 => [1/5] FROM docker.io/library/debian:bookworm@sha256:3d868b5eb908155f3784317b3dda2941df87bbbbaa4608f84881de66d9bb297b                                                     17.8s
 => => resolve docker.io/library/debian:bookworm@sha256:3d868b5eb908155f3784317b3dda2941df87bbbbaa4608f84881de66d9bb297b                                                      0.1s
 => => sha256:d52e4f012db158bb7c0fe215b98af1facaddcbaee530efd69b1bae07d597b711 49.55MB / 49.55MB                                                                             13.7s
 => => extracting sha256:d52e4f012db158bb7c0fe215b98af1facaddcbaee530efd69b1bae07d597b711                                                                                     3.9s
 => [2/5] COPY *sh /usr/local/bin/                                                                                                                                            0.4s
 => [3/5] RUN chmod +x /usr/local/bin/*.sh                                                                                                                                    0.3s
 => [4/5] RUN apt update && apt install -y --no-install-recommends     ca-certificates     curl     git     gnupg     nano     openssh-client     procps     unzip     wget  31.7s
 => ERROR [5/5] RUN /usr/local/bin/keygen.sh /ssh-dir                                                                                                                         0.2s
------
 > [5/5] RUN /usr/local/bin/keygen.sh /ssh-dir:
#0 0.173 /bin/sh: 1: /usr/local/bin/keygen.sh: not found
------
failed to solve: process "/bin/sh -c /usr/local/bin/keygen.sh /ssh-dir" did not complete successfully: exit code: 127
```

2023-07-27 16:26 UTC, gounthar commented
I have the same kind of problems within WLS2.
I'll try that on a real Linux machine.

2023-07-27 19:36 UTC, gounthar commented
It now works on my Windows machine, after cleaning up all my docker images, volumes, and containers with the `docker compose up --build --force-recreate maven` command... after the infamous dos2unix command on `keygen.sh`.
I don't know how to solve this one.

2023-07-27 19:36 UTC, gounthar approved these changes

2023-07-27 20:24 UTC, gounthar commented
It also works on my `aarch64` Linux machine.

2023-07-28 03:34 UTC, berviantoleo approved these changes
Wow. You are guys fast at work.

So far looks good.

🎉 

Thanks @ash-sxn & @gounthar 

---

I think we will need to fix the GitHub Action after this.

2023-07-28 04:12 UTC, ash-sxn commented
I was in docs office hours meeting with Mark & Meg just now. and we were trying this file on Windows and we got the same error as @gounthar 
```
=> ERROR [5/5] RUN /usr/local/bin/keygen.sh /ssh-dir                                                                                                                         0.2s
------
 > [5/5] RUN /usr/local/bin/keygen.sh /ssh-dir:
#0 0.173 /bin/sh: 1: /usr/local/bin/keygen.sh: not found
------
failed to solve: process "/bin/sh -c /usr/local/bin/keygen.sh /ssh-dir" did not complete successfully: exit code: 127
```
Mark recommended a quick fix by adding a .gitattributes file with this command `*.sh text elo=lf` and it worked 🎉
We tested two of the tutorial i.e node(windows with newly installed docker desktop) and python (on git bash) 

Thankyou @MarkEWaite 🙏🏼

2023-07-28 05:06 UTC, gounthar commented
That's great news, thanks a lot ,!

2023-07-28 06:49 UTC, merged