adding  & updating Readme
ash-sxn/GSoC-2023-docker-based-quickstart pull request #169
Opened 2023-08-14 11:11 UTC by ash-sxn

- fixes #161 
- Created a copy of `docker-compose.yaml` with build steps instead of images
- Which can be used by adding ` -f build-docker-compose.yaml` to the command `docker compose up -d` command to make this `docker compsoe -f build-docker-compose.yaml up -d`
- Updated the Readme file too

2023-08-14 13:13 UTC, gounthar commented on README.md
> +* The above command uses prebuild images, which is not always secure to pull for unknow source.
```suggestion
* The above command utilizes prebuilt images, which you might want to be cautious about as their source is not currently known or part of the Jenkins CI organization.
```

2023-08-14 13:15 UTC, gounthar requested changes

2023-08-14 13:15 UTC, gounthar commented on README.md
> +* eventually to make the command look something liks this `docker compose -f build-docker-compose.yaml up -d node` for build the Node Tutorial.
```suggestion
* Eventually, the command should resemble something like this: `docker compose -f build-docker-compose.yaml up -d node` to build the Node Tutorial.
```

2023-08-14 13:41 UTC, gounthar approved these changes
LGTM

2023-08-15 03:43 UTC, berviantoleo approved these changes

2023-08-19 02:11 UTC, merged