Feature/adding job
ash-sxn/GSoC-2023-docker-based-quickstart pull request #24
Opened 2023-06-15 10:23 UTC by ash-sxn

adding the job named `hello`
which creates a file named hello.txt with  `Hello World!` inside it with `echo Hello World! > hello.txt` in the first step
then view the file with `cat hello.txt`
Here's the Script used :
```
pipeline {
  agent any
  stages {

    stage('First') {
      steps {
        sh 'echo Hello World! > hello.txt'
      }
    }
    
    stage('Second') {
      steps {
        sh 'cat hello.txt'
      }
    }

  }
}
```
Please tell if I should use a different job 
- This resolves #18 
- Pinging mentors @jmMeessen @gounthar @berviantoleo

2023-06-15 12:28 UTC, gounthar requested changes
Thanks.
We don't need the files in the `builds` directory.

2023-06-15 13:17 UTC, ash-sxn commented
Sorry for that
I've deleted the build directory

2023-06-15 14:15 UTC, gounthar approved these changes

2023-06-19 03:05 UTC, ash-sxn commented on experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/dockerfiles/jobs/hello/config.xml
> +
how about adding sleep before the command?
like for 3-4 seconds

2023-06-20 12:46 UTC, jmMeessen commented on experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/dockerfiles/jobs/hello/config.xml
> +  <description>hello &#xd;
For the intended audience, the title of the job is not indicative. How about changing it to "(simple) demo job"

2023-06-20 12:46 UTC, jmMeessen commented on experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/dockerfiles/jobs/hello/config.xml
> +this is for the first sample job which first creates a file hello.txt with &apos;hello word!&apos; inside it and then cat this file</description>
Suggestion to improve the wording:

```suggestion
A simple pipeline based job. It creates a hello.txt  file with &apos;hello word!&apos; inside it and then displays the file.</description>
```

2023-06-22 07:08 UTC, ash-sxn commented
sorry for the delay, slipped out of the mind

2023-06-22 09:00 UTC, jmMeessen approved these changes
LGTM

2023-06-22 09:01 UTC, merged