(docs): for how to connect to UI on localhost
ash-sxn/GSoC-2023-docker-based-quickstart pull request #37
Opened 2023-06-21 00:02 UTC by ash-sxn

- fixes #33 
-  pinging mentors @berviantoleo @jmMeessen @gounthar

2023-06-21 08:16 UTC, gounthar commented on experimental_docker_compose_files/00_old_one_from_proposal/README.md
> +* after the containers are succefully running (check with `docker ps`). You can access the controller on [`http://localhost:8080`](http://localhost:8080)
```suggestion
* after the containers are successfully running (check with `docker compose ps`). You can access the controller on [`http://localhost:8080`](http://localhost:8080)
```

2023-06-21 08:17 UTC, gounthar requested changes

2023-06-22 09:06 UTC, jmMeessen approved these changes
We need to explain the special case of GitPod.
But at this stage the update to the readme is good enough. Needs to be revisited later (as well as the general documentation)

2023-06-22 09:09 UTC, berviantoleo approved these changes

2023-06-22 09:11 UTC, gounthar approved these changes

2023-06-22 12:13 UTC, jmMeessen commented
Just tried it out on Gitpod. The URL to call is something in this form: https://8080-ashsxn-gsoc2023dockerba-74xsllkyjcw.ws-eu100.gitpod.io/
We just need to tool it in such a way that it is straightforward for the user to start a session.

2023-06-22 12:19 UTC, gounthar commented
What about adding another bash script calling the existing key-generating script and another one that would detect the "machine" name under gitpod, and change the JCasc configuration accordingly?

2023-06-23 07:51 UTC, ash-sxn commented
I was thinking for the gitpod part, since it's mostly for beginners we could create a [`.gitpod.yaml`](https://www.gitpod.io/docs/references/gitpod-yml), that does all this and both  ssh-key update and running `docker compose up` too, right now since this is in a subdirectory and there are other examples, we can implement that for our main example

2023-06-23 08:28 UTC, ash-sxn commented
Isn't mentioning going to the `PORTS` section and clicking on the address a better solution for gitpod right now, and a popup also appears that leads to UI when the containers are built. We can implement @gounthar 's above script in the  .gipod.yml file for the final example, what do you guys think?

2023-06-23 12:25 UTC, gounthar commented
> I was thinking for the gitpod part, since it's mostly for beginners we could create a [`.gitpod.yaml`](https://www.gitpod.io/docs/references/gitpod-yml), that does all this and both ssh-key update and running `docker compose up` too, right now since this is in a subdirectory and there are other examples, we can implement that for our main example

I would prefer having a single point of entry, a `bash` script that would detect whether we are on MacOs, Linux or GitPod, and act accordingly.
You already have the parts to detect MacOs (`"$OSTYPE" == "darwin"*`) and GitPod (`-n "$GITPOD_WORKSPACE_URL"`).

2023-06-23 12:29 UTC, gounthar commented
> Isn't mentioning going to the `PORTS` section and clicking on the address a better solution for gitpod right now, and a popup also appears that leads to UI when the containers are built. We can implement @gounthar 's above script in the .gipod.yml file for the final example, what do you guys think? for updating URL part in jenkins.yaml I will add a script in #36. which we can later add to the `.gipod.yaml` file so it automatically updates jenkins.yaml file with correct URL when gitpod is started

I think it's a good idea to explain in the README how things work under GitPod. However, we still need to implement the JCasC modification part, where we will set the calculated value of the Jenkins controller instance as the default URL before starting the Docker Compose.

2023-06-23 13:04 UTC, ash-sxn commented
Okay,

> > I was thinking for the gitpod part, since it's mostly for beginners we could create a [`.gitpod.yaml`](https://www.gitpod.io/docs/references/gitpod-yml), that does all this and both ssh-key update and running `docker compose up` too, right now since this is in a subdirectory and there are other examples, we can implement that for our main example
> 
> I would prefer having a single point of entry, a `bash` script that would detect whether we are on MacOs, Linux or GitPod, and act accordingly. You already have the parts to detect MacOs (`"$OSTYPE" == "darwin"*`) and GitPod (`-n "$GITPOD_WORKSPACE_URL"`).

For linux and MacOS we can set default value to `http://127.0.0.1:8080` and for gitpod we can have a script  but for `yq`, since it's not installed by default, we can put a .gitpod.yaml file that install the `yq` command when gitpod is launched

2023-06-23 13:08 UTC, ash-sxn commented
> > I was thinking for the gitpod part, since it's mostly for beginners we could create a [`.gitpod.yaml`](https://www.gitpod.io/docs/references/gitpod-yml), that does all this and both ssh-key update and running `docker compose up` too, right now since this is in a subdirectory and there are other examples, we can implement that for our main example
> 
> I would prefer having a single point of entry, a `bash` script that would detect whether we are on MacOs, Linux or GitPod, and act accordingly. You already have the parts to detect MacOs (`"$OSTYPE" == "darwin"*`) and GitPod (`-n "$GITPOD_WORKSPACE_URL"`).

For Linux and macOS we can have `http://127.0.0.1:8080` as default and script for gitpod that changes that, but since it needs `yq`  command, I can make `.gitpod.yaml` file that installs `yq`  on gitpod

2023-06-23 13:17 UTC, gounthar commented
> For Linux and macOS we can have `http://127.0.0.1:8080` as default and script for gitpod that changes that, but since it needs `yq` command, I can make `.gitpod.yaml` file that installs `yq` on gitpod
Fine with me! 👍

2023-06-23 16:03 UTC, merged