Feature/maven tutorial
ash-sxn/GSoC-2023-docker-based-quickstart pull request #70
Opened 2023-06-28 18:12 UTC by ash-sxn

- resolves #39 
- pinging mentors @gounthar @berviantoleo @jmMeessen

2023-06-28 19:20 UTC, gounthar requested changes
The Maven job is missing, right?
See https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/blob/368ddf627cb55950e020655b9e84c4d2008e0693/experimental_docker_compose_files/maven/dockerfiles/jobs/simple-java-maven-app/config.xml .

2023-06-28 19:20 UTC, gounthar commented on experimental_docker_compose_files/03_maven_tutorial/dockerfiles/Dockerfile
> +FROM jenkins/jenkins:2.401.1-lts
```suggestion
FROM jenkins/jenkins:2.401.2-lts
```

2023-06-28 19:20 UTC, gounthar commented on experimental_docker_compose_files/03_maven_tutorial/dockerfiles/agent/Dockerfile
> +ENV PATH="${M2_HOME}/bin/:${PATH}"
```suggestion
ENV M2_HOME="/opt/maven"
ENV PATH="${M2_HOME}/bin/:${PATH}"
RUN echo "PATH=${PATH}" >> /etc/environment
```

2023-06-28 19:24 UTC, gounthar commented on experimental_docker_compose_files/03_maven_tutorial/dockerfiles/plugins.txt
> +mailer:457.v3f72cb_e015e5
```suggestion
mailer:457.v3f72cb_e015e5
pipeline-graph-view:191.vc6da_9d3eb_70a
```

2023-06-28 19:34 UTC, gounthar commented on experimental_docker_compose_files/03_maven_tutorial/fork-and-clone.sh
> +CLONE_DIR=$(pwd)/$REPO_NAME
```suggestion
CLONE_DIR=$(pwd)/../../$REPO_NAME
```

2023-06-29 04:58 UTC, ash-sxn commented
@gounthar
Yes, I've not added the job. I was thinking setting that up will be a good part for the beginner users.
I will add the `fork-and-clone.sh` to the init script, I also think It will be better to do that with init script 
and I was also wondering about the slides for the presentation. I'll share them on Gitter after creating them. for feedback.

2023-06-29 18:50 UTC, gounthar requested changes
Please see all the files that end up with a 🚫 or equivalent.
That means an empty end line is missing. That is not [POSIX compliant](https://www.techtarget.com/whatis/definition/POSIX-Portable-Operating-System-Interface).
Could you please correct it?

2023-06-30 12:54 UTC, gounthar commented on jenkins_init.sh
> +  bash $tutorial_path/keygen.sh $tutorial_path
Why not call the script directly?
Are there any challenges or considerations that I may not be aware of?

2023-06-30 12:55 UTC, gounthar approved these changes

2023-06-30 12:56 UTC, merged